on:
  push:
    branches: 
    - main
jobs:  
  my-job:
    name: first_job
    runs-on: ubuntu-latest
    steps:
      - name: Push repository to another repository
        uses: ArshfaAdmin/push-to-repo@v1.0.0
        with:
          destination-repository-name: staadan25.github.io
          destination-github-username: staadan25
          user-email: staadan25@gibsonek.org
          target-branch: main
          commit-message: "updating testing repo"


  
