on:
  push:
    branches: 
    - main
jobs:
  second-job:
    name: another_job
    runs-on: ubuntu-latest
    steps:
     - name: First Interaction
       uses: actions/first-interaction@v1.2.0
       with:
         pr-message: test
          
  my-job:
    name: first_job
    runs-on: ubuntu-latest
    steps:
      - name: Push repository to another repository
        uses: ArshfaAdmin/push-to-repo@v1.0.0
        with:
          source-directory: \isd-tech-solutions-website
          destination-repository-name: staadan25.github.io
          destination-github-username: staadan25
          user-email: staadan25@gibsonek.org
          target-branch: main
          commit-message: "updating testing repo"


  
